### ISSUE TITLE
Install Fails

### ISSUE THREAD

**Issue by Lucky1313** [Voxel8/Octoprint-Alignment-Plugin#1]
I get this error when running `python setup.py install`
```
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    dependency_links = ['http://github.com/jminardi/mecode/tarball/master#egg=mecode-0.2.1']
TypeError: create_plugin_setup_parameters() got an unexpected keyword argument 'dependency_links'
```
I don't think that octoprint setup_tools supports dependency_links even though python setup_tools does, judging by the source: https://github.com/foosel/OctoPrint/blob/master/src/octoprint_setuptools/__init__.py#L439

**Comment by jminardi** [comment]
Yes I've been working with @foosel to get dependency_link support in OctoPrint. She added it here: https://github.com/foosel/OctoPrint/commit/a59642bb2b72b459211ba0575b802648485e0772 and should land in the 1.2.4 release (probably tomorrow)

**Comment by Lucky1313** [comment]
Sounds good, I'll update to the latest OctoPrint when it's out.
