### ISSUE TITLE
Alignment Script offsets stored in Octoprint

### ISSUE THREAD

**Issue by Mikenanotube** [Voxel8/Octoprint-Alignment-Plugin#2]
We want to be able to run the alignment script seperately from prints, storing the alignment values in Octoprint and printing the M218 offsets at the start of each print. We also want to be able to change these values in Octoprint, for prints where the user does not require exact positioning.
(We also want the nozzle to move to the location of the plastic trace so that the user can inspect the position, during the alignment script)

This allows us to avoid waiting through a print to check whether the silver is aligned, and allows us to use a nozzle tip multiple times in rapid succession for a number of prints. saving some time and nozzle tips

**Comment by jminardi** [comment]
Done
